### ISSUE TITLE
Kill Counter v2.0.lua

### ISSUE THREAD

**Issue by AHITMAN** [Chalwk77/HALO-SCRIPT-PROJECTS#126]
**Describe the bug**
stack traceback:
        [string "Kill Counter v2.0"]:771: in function <[string "Kill Counter v2.0"]:770>
        [C]: at 0x10066090
        [C]: in function 'ipairs'
        [string "Kill Counter v2.0"]:670: in function 'getIP'
        [string "Kill Counter v2.0"]:519: in function <[string
EventCallback >> OnPlayerKill >> Lua Error: [string "Kill Counter v2.0"]:670: bad argument #1 to 'ipairs' (table expected, got nil)
AHITMAN was killed by the server

**To Reproduce**
use the "reload" command in the server console

**Please complete the following information:**
 - EXTENSION: [ SAPP]
 - SAPP VERSION: 10.2.1]
 - Script Version [none as far as I can read]

**Additional context**
script still works fine as far as ive tested it.

**Comment by Chalwk77** [comment]
What the?!

Not sure how this happened but the Kill Counter v2.0 script has been overwritten by the contents of another script (Upgrade System). The original Kill Counter v2.0 script was less than 20 lines of code.

I removed the actual Upgrade System from my GitHub many moons ago, due to being a trash project.

I don't plan on supporting and updating this accidentally "preserved" version.
I do, however, need to restore the original Kill Counter v2.0 script.

**Comment by AHITMAN** [comment]
ok thanks man appreciate it.
